name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build & push Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.AWS_ECR_REPO }}:latest .
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO }}
          docker push ${{ secrets.AWS_ECR_REPO }}:latest
      - name: Terraform deploy
        run: |
          cd deploy/terraform/aws
          terraform init
          terraform apply -auto-approve
